### ISSUE TITLE
KeyError: 'SerializableManager' on db migrations in Django 1.10+ (1.11)

### ISSUE THREAD

**Issue by dev0088** [agilgur5/django-serializable-model#4]
I installed `0.0.4` version again.
To update database, I ran this:
```
python manage.py makemigrations
```

Then I got this error: `KeyError: 'SerializableManager'`

```
Traceback (most recent call last):
  File "/Volumes/Data/work/env3/lib/python3.6/site-packages/django/db/models/options.py", line 409, in base_manager
    return self.managers_map[base_manager_name]
KeyError: 'SerializableManager'

....
ValueError: SerializableModel has no manager named 'SerializableManager'
```

I can't use this package, still.

**Comment by agilgur5** [comment]
Ah yep that's a compatibility bug.
This is a Django 1.10+ ism since it added the `base_manager_name` field. I've never used Django 1.10+ (one of the reasons it's listed as "likely works"), and just followed the [docs on it](https://docs.djangoproject.com/en/1.10/topics/db/managers/#base-managers) but the docs have no example usage 😅 .

Apparently the correct "name" in this case is supposed to be `'objects'`, not `'SerializableManager'`.
Apparently you're supposed to use the [string version of the name of the attribute that is set to the instance](https://stackoverflow.com/a/48124863/3431180) and I didn't know that, sorry.

I'll have to add a PR to the Django docs to improve this as this could be a lot clearer with an example.

**Comment by dev0088** [comment]
Thanks. 
Hope I'll be able to use this package, as soon as possible. :)

**Comment by agilgur5** [comment]
Yea I'll throw up an alpha release in a bit.

Alpha because maybe there's some other issues in 1.10+ I don't know 😕 . If only adding tests to this weren't quite so difficult/tedious (lots of fixtures/setup, including multiple Django versions set-up too).

**Comment by dev0088** [comment]
Make sense. :)

**Comment by agilgur5** [comment]
I think you could probably workaround this if you wanted to by setting the `base_manager_name` yourself:

```python
class YourModel(SerializableModel):
     ...

    class Meta:
        base_manager_name = 'objects'
```

potentially might need to set `objects = SerializableManager()` directly, but shouldn't need to since it's inherited.

**Comment by dev0088** [comment]
I gonna try it tomorrow. I worked too much, today. So I'm already a squeezed orange. 
I'll try it, agin, tomorrow. And I'll let you know the result.
Thanks for your help!

**Comment by agilgur5** [comment]
This particular issue should be fixed in [`v0.0.5-alpha.1`](https://github.com/agilgur5/django-serializable-model/releases/tag/v0.0.5-alpha.1). Might need to specify the version when re-installing as it's a [pre-release](https://pypi.org/project/django-serializable-model/#history).

dat turnaround time tho 😆 . happened to be at my computer working on another library anyway haha. thanks for sticking through the churn and pointing out issues @ninjadev999 ! :)

**Comment by agilgur5** [comment]
Hey @ninjadev999 , were you able to try out `v0.0.5-alpha.1`? Did you run into any other issues/have any other feedback? Will publish `v0.0.5` if all good

**Comment by agilgur5** [comment]
Ok, I didn't hear back from you @ninjadev999 , so I've released [v0.0.5](https://github.com/agilgur5/django-serializable-model/releases/tag/v0.0.5) that includes the alpha changes and a typo fix for `editable` fields.

**Comment by ninjadev999** [comment]
@agilgur5 , I was very busy. I'll check the release version v0.0.5 within 2 days and I'll let you know.
Thank you!

**Comment by dev0088** [comment]
@agilgur5 , I was very busy. I'll check the release version v0.0.5 within 2 days and I'll let you know.
Thank you!

**Comment by agilgur5** [comment]
As of #6 and [v0.0.6](https://github.com/agilgur5/django-serializable-model/releases/tag/v0.0.6), I've now added tests with [92% code coverage](https://codecov.io/gh/agilgur5/django-serializable-model) and a [matrix](https://travis-ci.org/agilgur5/django-serializable-model) that confirms compatibility for Django 2.2, 1.11, 1.9, and 1.5 as well as Python 3.5, 3.4, and 2.7.
So these types of issues should mostly be in the past now 🙂 

Also noting that the fix for this in https://github.com/agilgur5/django-serializable-model/commit/8c0d5715d14f544fa8fca66b642ea86454321f43 broke <1.10, which the new test matrix discovered, and this was later fixed in https://github.com/agilgur5/django-serializable-model/commit/803155bf6e3d36ef43539cd6b13b437e12294edd so that it works for both <1.10 and 1.10+
